name: Build And Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: yarn install --immutable --immutable-cache

      - name: Build
        run: |
          yarn run build
          7za a build.zip ./dist/*

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          outputs: type=tar,dest=docker.tar
          tags: |
            green1052/auto-web-attendance:latest
            green1052/auto-web-attendance:latest:${{github.ref_name}}
          platforms: linux/amd64,linux/arm64

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          prerelease: false
          files: |
            build.zip
            docker.tar
